#!/bin/bash

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Building client application"
COMMAND=$(cat <<EOF
cd "/app" &&
new_path="\$(find / -name npm | tail -1 | xargs -I % sh -c "dirname %")" &&
PATH="\$PATH:\$new_path" &&
PATH="\$PATH:\$(npm bin)" &&
npm install grunt &&
npm install grunt-cli &&
npm update &&
grunt dist --force
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Built Node"
